import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.Scanner;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        Scanner input = new Scanner(System.in);
            //word
            System.out.println("enter a sentence or a word");
            String stringUserEntered = input.nextLine();
            //key
            System.out.println("enter a number as key");
            Integer key = input.nextInt();

            System.out.println(stringUserEntered + key);
            Encode encode = new Encode(key, stringUserEntered);
            String encodedString = encode.encodeWord(key, stringUserEntered);
            System.out.println(encodedString);


    }
}
