import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
//        System.out.println(new App().getGreeting());
//        System.out.println(new App().getMessage());
//
//        BufferedReader bufferedReader = new BufferedReader(new InputStreamReader(System.in));
//        System.out.println("enter a sentence");
//        try {
//            String stringUserEntered = bufferedReader.readLine();
//            ScrabbleScorer scrabbleScorer = new ScrabbleScorer();
//            Integer scrabbleScorerResult = scrabbleScorer.calculateScore(stringUserEntered);
//            System.out.println(scrabbleScorerResult);
//
//        } catch (IOException e) {
//            e.printStackTrace();
//        }
    }
}
